In [1]:
# Import Libraries
import pandas as pd
import numpy as np
import os

In [2]:
# Import City Data
Albany1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Albany, NY/Albany 1.csv")
Ash1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Asheville, NC/Ash 1.csv")
Austin1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Austin, TX/Austin 1.csv")
Boston1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Boston, Mass/Boston 1.csv")
Boz1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Bozeman, MT/Boz 1.csv")
Bro1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Broward County, FL/listings (10).csv")
Cam1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Cambridge, Mass/Cam1.csv")
Chi1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Chicago, IL/Chicago 1.csv")
Clark1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Clark County, NV/Clark 1.csv")
Col1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Columbus, OH/Columbus 1.csv")
Dallas1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Dallas, TX/Dallas 1.csv")
Den1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Denver, CO/Denver 1.csv")
FW1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Fort Worth, TX/Fort Worth 1.csv")
Ha1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Hawaii/Ha1.csv")
Jer1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Jersey City, NJ/JerseyCity1.csv")
LA1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Los Angeles, CA/LA1.csv")
Nash1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Nashville, TN/Nash 1.csv")
New1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /New Orleans, LA/listings (12).csv")
NYC1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /New York City, NY/listings (10).csv")
new1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Newark, NJ/listings (21).csv")
Oak4=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Oakland, CA/listings.csv")
Pac1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Pacific Grove, CA/listings (4).csv")
Port1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Portland, OR/listings (8).csv")
RI1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Rhode Island/listings (1).csv")
Ro1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Rochester, NY/listings (1).csv")
s1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Salem, OR/listings (1).csv")
sd1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /San Diego, CA/listings (1).csv")
sf1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /San Fransico, CA/listings (4).csv")
sm1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /San Mateo County, CA/listings (8).csv")
sc1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Santa Clara County, CA/listings (12).csv")
scz1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Santa Cruz County, CA/listings (16).csv")
sea1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Seattle/listings (1).csv")
twin1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Twin Cities MSA, Minnesota/listings (1).csv")
DC1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Washington DC/listings (4).csv")

/var/folders/xq/j07ql7ls565cz8lmytmw14b40000gn/T/ipykernel_9668/2384567543.py:7: DtypeWarning: Columns (68) have mixed types. Specify dtype option on import or set low_memory=False.
  Bro1=pd.read_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/Original Air BNB csv /Broward County, FL/listings (10).csv")

In [3]:
# Adding Listing City Column
Albany1['listing_city']= 'Albany, NY'
Ash1['listing_city']= 'Asheville, NC'
Austin1['listing_city']= 'Austin, TX'
Boston1['listing_city']= 'Boston, MA'
Boz1['listing_city']= 'Bozeman, MT'
Bro1['listing_city']= 'Broward County, FL'
Cam1['listing_city']= 'Cambridge, MA'
Chi1['listing_city']= 'Chicago, IL'
Clark1['listing_city']= 'Clark County, NV'
Col1['listing_city']= 'Columbus, OH'
Dallas1['listing_city']= 'Dallas, TX'
Den1['listing_city']= 'Denver, CO'
FW1['listing_city']= 'Fort Worth, TX'
Ha1['listing_city'] = 'Hawaii, HI'
Jer1['listing_city'] = 'Jersey City, NJ'
LA1['listing_city']='Los Angeles, CA'
Nash1['listing_city']= 'Nashville, TN'
New1['listing_city'] = 'New Orleans, LA'
NYC1['listing_city'] = 'New York City, NY'
new1['listing_city']= 'Newark, NJ'
Oak4['listing_city']= 'Oakland, CA'
Pac1['listing_city']= 'Pacific Grove, CA'
Port1['listing_city']= 'Portland, OR'
RI1['listing_city']= 'Rhode Island, RI'
Ro1['listing_city']= 'Rochester, NY'
s1['listing_city']= 'Salem, OR'
sd1['listing_city']= 'San Diego, CA'
sf1['listing_city']= 'San Fransico, CA'
sm1['listing_city']= 'San Mateo County, CA'
sc1['listing_city']= 'Santa Clara County, CA'
scz1['listing_city']= 'Santa Cruz, CA'
sea1['listing_city']= 'Seattle, WA'
twin1['listing_city']= 'Twin Cities MSA, MN'
DC1['listing_city']= 'Washington, DC'

In [4]:
df=pd.concat([DC1, twin1, sea1, scz1, sc1, sm1, sf1, sd1, s1, Ro1, RI1, Port1, Pac1, Oak4, new1, NYC1, New1, Nash1, LA1, Jer1, Ha1, FW1, Den1, Dallas1, Col1, Clark1, Chi1, Cam1, Bro1, Boz1, Boston1, Austin1, Ash1, Albany1], axis=0)

In [5]:
df.shape

(288474, 76)

In [6]:
path=r'/Users/sarahboller/Desktop/CF Achievement 6/02 Data'

In [7]:
df.to_csv(os.path.join(path, 'merged city recent data only.csv'))

In [8]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month',
       'listing_city'],
      dtype='object')

In [9]:
df=df.drop(columns=['last_scraped','id','listing_url', 'scrape_id','source', 'name',
                    'description', 'neighborhood_overview', 'picture_url', 'host_id','host_name',
                    'host_url', 'host_location', 'host_about', 'host_response_time', 'host_response_rate',
                    'host_acceptance_rate', 'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood',
                    'host_listings_count', 'host_verifications', 'host_has_profile_pic', 'host_identity_verified',
                    'neighbourhood', 'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'bathrooms', 'bedrooms',
                    'amenities', 'minimum_nights', 'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights',
                    'minimum_maximum_nights', 'maximum_maximum_nights', 'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm',
                    'calendar_updated', 'availability_30', 'availability_60', 'availability_90','availability_365', 
                    'calendar_last_scraped', 'calculated_host_listings_count', 'calculated_host_listings_count_entire_homes',
                    'calculated_host_listings_count_private_rooms','calculated_host_listings_count_shared_rooms','license',
                    'number_of_reviews_ltm','number_of_reviews_l30d'])

In [10]:
df.shape

(288474, 25)

In [11]:
df.dtypes

host_since                      object
host_is_superhost               object
host_total_listings_count      float64
latitude                       float64
longitude                      float64
property_type                   object
room_type                       object
accommodates                     int64
bathrooms_text                  object
beds                           float64
price                           object
has_availability                object
number_of_reviews                int64
first_review                    object
last_review                     object
review_scores_rating           float64
review_scores_accuracy         float64
review_scores_cleanliness      float64
review_scores_checkin          float64
review_scores_communication    float64
review_scores_location         float64
review_scores_value            float64
instant_bookable                object
reviews_per_month              float64
listing_city                    object
dtype: object

In [12]:
# Check for missing values:
df.isnull().sum()

host_since                        35
host_is_superhost               1863
host_total_listings_count         35
latitude                           0
longitude                          0
property_type                      0
room_type                          0
accommodates                       0
bathrooms_text                   369
beds                           17852
price                          25039
has_availability               10316
number_of_reviews                  0
first_review                   65618
last_review                    65618
review_scores_rating           65490
review_scores_accuracy         65578
review_scores_cleanliness      65566
review_scores_checkin          65600
review_scores_communication    65570
review_scores_location         65606
review_scores_value            65607
instant_bookable                   0
reviews_per_month              65618
listing_city                       0
dtype: int64

In [13]:
df_no_reviews= df[df['first_review'].isnull()==False]

In [14]:
df_no_reviews.to_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/clean_no_reviews.csv")

In [15]:
df.isnull().sum()

host_since                        35
host_is_superhost               1863
host_total_listings_count         35
latitude                           0
longitude                          0
property_type                      0
room_type                          0
accommodates                       0
bathrooms_text                   369
beds                           17852
price                          25039
has_availability               10316
number_of_reviews                  0
first_review                   65618
last_review                    65618
review_scores_rating           65490
review_scores_accuracy         65578
review_scores_cleanliness      65566
review_scores_checkin          65600
review_scores_communication    65570
review_scores_location         65606
review_scores_value            65607
instant_bookable                   0
reviews_per_month              65618
listing_city                       0
dtype: int64

In [16]:
df= df[df['first_review'].isnull()==False]

In [17]:
df.isnull().sum()

host_since                        21
host_is_superhost               1619
host_total_listings_count         21
latitude                           0
longitude                          0
property_type                      0
room_type                          0
accommodates                       0
bathrooms_text                   149
beds                           12034
price                          16866
has_availability                6703
number_of_reviews                  0
first_review                       0
last_review                        0
review_scores_rating               0
review_scores_accuracy            88
review_scores_cleanliness         76
review_scores_checkin            110
review_scores_communication       80
review_scores_location           116
review_scores_value              117
instant_bookable                   0
reviews_per_month                  0
listing_city                       0
dtype: int64

In [18]:
df= df[df['price'].isnull()==False]

In [19]:
df.isnull().sum()

host_since                       19
host_is_superhost              1574
host_total_listings_count        19
latitude                          0
longitude                         0
property_type                     0
room_type                         0
accommodates                      0
bathrooms_text                  132
beds                           1871
price                             0
has_availability                  4
number_of_reviews                 0
first_review                      0
last_review                       0
review_scores_rating              0
review_scores_accuracy           74
review_scores_cleanliness        74
review_scores_checkin            91
review_scores_communication      73
review_scores_location           94
review_scores_value              95
instant_bookable                  0
reviews_per_month                 0
listing_city                      0
dtype: int64

In [20]:
df= df[df['beds'].isnull()==False]
df= df[df['host_is_superhost'].isnull()==False]
df= df[df['bathrooms_text'].isnull()==False]
df= df[df['host_since'].isnull()==False]
df= df[df['review_scores_value'].isnull()==False]

In [21]:
df.isnull().sum()

host_since                     0
host_is_superhost              0
host_total_listings_count      0
latitude                       0
longitude                      0
property_type                  0
room_type                      0
accommodates                   0
bathrooms_text                 0
beds                           0
price                          0
has_availability               4
number_of_reviews              0
first_review                   0
last_review                    0
review_scores_rating           0
review_scores_accuracy         2
review_scores_cleanliness      4
review_scores_checkin          6
review_scores_communication    1
review_scores_location         7
review_scores_value            0
instant_bookable               0
reviews_per_month              0
listing_city                   0
dtype: int64

In [22]:
df= df[df['has_availability'].isnull()==False]
df= df[df['review_scores_accuracy'].isnull()==False]
df= df[df['review_scores_cleanliness'].isnull()==False]
df= df[df['review_scores_checkin'].isnull()==False]
df= df[df['review_scores_communication'].isnull()==False]
df= df[df['review_scores_location'].isnull()==False]

In [23]:
df.isnull().sum()

host_since                     0
host_is_superhost              0
host_total_listings_count      0
latitude                       0
longitude                      0
property_type                  0
room_type                      0
accommodates                   0
bathrooms_text                 0
beds                           0
price                          0
has_availability               0
number_of_reviews              0
first_review                   0
last_review                    0
review_scores_rating           0
review_scores_accuracy         0
review_scores_cleanliness      0
review_scores_checkin          0
review_scores_communication    0
review_scores_location         0
review_scores_value            0
instant_bookable               0
reviews_per_month              0
listing_city                   0
dtype: int64

In [24]:
# Check for dups
df_dups=df[df.duplicated()]

In [25]:
df_dups

,host_since,host_is_superhost,host_total_listings_count,latitude,longitude,property_type,room_type,accommodates,bathrooms_text,beds,...,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,reviews_per_month,listing_city
6085,2013-04-07,t,46.0,37.788990,-122.412791,Room in hotel,Private room,4,1 private bath,2.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,t,0.09,"San Fransico, CA"
6088,2013-04-07,t,46.0,37.788990,-122.412791,Room in hotel,Private room,4,1 private bath,2.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,t,0.09,"San Fransico, CA"
6245,2021-02-22,t,1174.0,36.155507,-86.775692,Entire condo,Entire home/apt,4,1 bath,2.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,f,0.10,"Nashville, TN"
9091,2022-08-17,f,283.0,36.107613,-115.161596,Private room in resort,Private room,8,2 baths,4.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,t,0.05,"Clark County, NV"
9225,2022-08-19,f,104.0,36.108824,-115.168488,Private room in resort,Private room,4,1 private bath,2.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,t,0.94,"Clark County, NV"
9311,2022-08-18,f,23.0,36.107548,-115.169425,Private room in resort,Private room,4,1 private bath,2.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,t,0.11,"Clark County, NV"
9391,2022-08-19,f,104.0,36.108824,-115.168488,Private room in resort,Private room,6,2 baths,3.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,t,0.94,"Clark County, NV"
9392,2022-08-19,f,104.0,36.108824,-115.168488,Private room in resort,Private room,6,2 baths,3.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,t,0.94,"Clark County, NV"
9406,2022-08-19,f,104.0,36.108824,-115.168488,Private room in resort,Private room,6,2 baths,3.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,t,0.94,"Clark County, NV"
10731,2022-09-16,t,15.0,36.108300,-115.165890,Room in hotel,Private room,8,3 baths,4.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,t,0.10,"Clark County, NV"
10989,2022-08-17,f,283.0,36.107613,-115.161596,Private room in resort,Private room,8,2 baths,4.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,t,0.10,"Clark County, NV"
14352,2022-08-19,f,104.0,36.108824,-115.168488,Private room in resort,Private room,2,1 private bath,1.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,t,0.94,"Clark County, NV"
15581,2020-07-10,f,1394.0,36.139879,-115.160899,Entire condo,Entire home/apt,2,1 bath,1.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,f,0.61,"Clark County, NV"

In [26]:
df.shape

(202297, 25)

In [27]:
df1=df.drop_duplicates()

In [28]:
df1.shape

(202284, 25)

In [29]:
df1.to_csv("/Users/sarahboller/Desktop/CF Achievement 6/02 Data/clean recent city merged 3182024.csv")